# Generated by Django 5.0 on 2024-03-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_gallery_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(default='gallery.jpg', upload_to='gallery'),
        ),
    ]
