# Generated by Django 5.0 on 2024-03-18 07:12

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_gallery_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz', length=10, max_length=10, prefix='', unique=True),
        ),
    ]
