# Generated by Django 5.0 on 2024-03-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_gallery_gallery_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='slug',
        ),
    ]
