# Generated by Django 5.0 on 2024-03-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'ordering': ['country'], 'verbose_name_plural': 'Taxes'},
        ),
    ]
