# Generated by Django 5.0 on 2024-04-02 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_shipping_amount_cart_shipping_cost_and_more'),
        ('vendor', '0002_alter_vendor_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
