# Generated by Django 5.0 on 2024-04-07 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_cartorder_stripe_session_id'),
        ('vendor', '0002_alter_vendor_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitem',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
