# Generated by Django 5.0 on 2024-04-07 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_cartorderitem_vendor'),
        ('vendor', '0004_alter_vendor_mobile_alter_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
