# Generated by Django 5.0 on 2024-05-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_product_rating_alter_product_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, default='gallery.jpg', null=True, upload_to='gallery'),
        ),
    ]
