# Generated by Django 5.0 on 2024-05-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(blank=True, default='gallery.jpg', null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, default='product.jpg', null=True, upload_to='products'),
        ),
    ]
